# Generated by Django 6.1.1 on 2026-09-04 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('file_path', models.CharField(max_length=500, unique=True, verbose_name='Путь к файлу')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный токен')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
