# Generated by Django 6.1.1 on 2026-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='Путь к файлу'),
        ),
    ]
